import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul>
          {" "}
          <Link href="/">
            {" "}
            <li>Home</li>
          </Link>
          <Link href="/about">
            {" "}
            <li>about</li>
          </Link>
          <Link href="/contact">
            {" "}
            <li>contact</li>
          </Link>
        </ul>
        {children}
      </body>
    </html>
  );
}
